version: 2.1

workflows:
  sample:
    jobs:
      - build-bionic
jobs:

  build-bionic:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
          docker_layer_caching: true
      - run:
          name: Build Step
          no_output_timeout: 1.5h
          command: |
            ./scripts/docker/build.sh --bionic --remote astrobee test_astrobee
