version: 1
name: Astrobee-New
stages:
  - name: build
    type: ci
    spec:
      steps:
        - name: Git Checkout
          type: script
          spec:
            run: git checkout 271b6906c626ca874ebba4106444995d44092aab
        - name: Run
          type: script
          spec:
            run: sleep 100000
